### ISSUE TITLE
Define color definitions for koe colorscheme

### ISSUE THREAD

**Issue by hovsater** [koekeishiya/dotfiles#11]
Hey, first of all. Thank you for the `koe` colorscheme. It's wonderful. I've been using it primarily for Ruby, JavaScript, Go and nim development and it's been a blast. 🎉 

However, at this point, I'm trying to define "what colors goes where" so that I can unify my experience across all languages. Given that you primarily work in C and C++, using those as reference make sense.

This is what I've deduced so far:

- Identifiers are white
- Comments are green
- Constants are cyan
- function names dark gray
- Strings and primitives are dark blue (I'm not sure about this one)
- Types are green

Am I missing something?

Some questions:

- Color of a visual selection in Vim? (mine is red with black text)
- Color of status line in Vim? Mine is dark gray on black (hardly visible)
- Color of a visual selection in Tmux? (mine is brown with black text. Should it match Vim?)

Would you be interested breaking out the colorscheme into its own repository? In that way, I can backport whatever changes I'm making as well. If you're not up for it, I totally understand. Just a suggestion. 🙂

**Comment by asmvik** [comment]
I don't mind doing that, but I haven't actually made a colorscheme really in a formal sense.
Right now the colors specified in the nvim theme simply refer to the terminal color slot that I used.

E.g: color15 (alt. white) refers to #d8d8d8, and color7 (white) #c0b18b, where the former is the color used for identifiers and the latter is used as the normal text color.

**Comment by asmvik** [comment]
I'll try to clean my config a bit and update my dotfiles. I use vim-airline for the statusbar and forgot that I had a modified gruvbox theme for vim-airline.

**Comment by hovsater** [comment]
@koekeishiya thanks, appreciate it. If I can help out with anything, I'd be more than happy to help. 🙂

**Comment by asmvik** [comment]
I've updated the nvim colorscheme to reference the terminal colors between 0-15 instead of using names of colors. You can find the colors used and the slot they go into in the list below. There is a section at the top of the file that says what each category correspond to (identifiers, comment, constants, etc).

I've also added the vim-airline scheme: https://github.com/koekeishiya/dotfiles/tree/master/nvim/autoload/airline/themes

The colors are set to the following values in my terminal:
```
# The foreground color
foreground       #c0b18b

# The background color
background       #262626

# The foreground for selections
selection_foreground #2f2f2f

# The background for selections
selection_background #d75f5f

# black
color0   #2f2f2f
color8   #656565

# red
color1   #d75f5f
color9   #d75f5f

# green
color2    #d4d232
color10   #8fee96

# yellow
color3    #af865a
color11   #cd950c

# blue
color4   #22c3a1
color12  #22c3a1

# magenta
color5   #775759
color13  #775759

# cyan
color6   #84edb9
color14  #84edb9

# white
color7   #c0b18b
color15  #d8d8d8
```

> Color of a visual selection in Vim? (mine is red with black text)
Color of a visual selection in Tmux? (mine is brown with black text. Should it match Vim?)

Both of these look that way for me. The difference is just so I can easily distinguish between a tmux selection and a nvim selection.

> Color of status line in Vim? Mine is dark gray on black (hardly visible)

This should be resolved if you install vim-airline and apply the theme above.

> This is what I've deduced so far:

>Identifiers are white
Comments are green
Constants are cyan
function names dark gray
Strings and primitives are dark blue (I'm not sure about this one)
Types are green

Mostly correct except for the identifiers part. If you cross-reference the updated theme with the colors listed in this post you'll get a proper mapping that you should be able to port for other languages.

I didn't bother with separating the theme in a separate repo, so hopefully this information will make it easier for you to make something proper out of it.

**Comment by asmvik** [comment]
Updated screenshot:
<img width="1440" alt="shot1" src="https://user-images.githubusercontent.com/6175959/76802655-70208e00-67d8-11ea-9451-9954326229c2.png">

**Comment by hovsater** [comment]
Thanks a lot for the detailed response and the updates to your dotfiles! I now have everything I need to unify colors across all languages. 👍 🙂

**Comment by Poorchop** [comment]
Do you plan on releasing this as an official theme? I like the terminal colors.
